---

platform: linux

image_resource:
  type: registry-image
  source:
    repository: node
    tag: 10
inputs:
  - name: express_gql
  - name: dependency-cache

run:
  path: express_gql/ci/scripts/run_tests.sh
