---
resource_types:
  - name: npm-cache
    type: docker-image
    source:
      repository: ymedlop/npm-cache-resource
      tag: latest
resources:
  - name: express_gql
    type: git
    source: &repo-source
      uri: https://github.com/vijaykrishnavanshi/express-graphql-boilerplate.git
      branch: master
  - name: dependency-cache
    type: npm-cache
    source:
      <<: *repo-source
      paths:
        - package.json
jobs:
  - name: Install dependencies
    plan:
      - get: express_gql
        trigger: true
      - get: dependency-cache
  - name: Run tests
    plan:
      - get: express_gql
        trigger: true
        passed: [Install dependencies]
      - get: dependency-cache
        passed: [Install dependencies]
      # - task: run mongodb
      #   config:
      #     platform: linux
      #     image_resource:
      #       type: docker-image
      #       source:
      #         repository: mongodb
      #     run:
      #       path: mongodb
      #       args: ["27017:27017"]
      #   passed: [MongoDB Running]
      - task: run the test suite
        file: express_gql/ci/tasks/run_tests.yml
